import Head from 'next/head';
import styles from '../styles/Over.module.css';

export default function Over() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <h1>Game over screen</h1>
      </main>
    </div>
  );
}
